name: ai_super_app
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons:
  permission_handler:
  flutter_dotenv:
  shared_preferences:
  http:
  path:
  # chat bots
  # openai:
  google_generative_ai: ^0.2.0
  # image recognition
  image_picker:
  google_mlkit_image_labeling:
  google_mlkit_smart_reply:
  # real-time language translation
  speech_to_text:
  flutter_tts: # Text-to-speech
  translator: # google translator
  # document translation
  file_picker:
  read_pdf_text:

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

# dependency_overrides:
#   google_mlkit_barcode_scanning:
#     path: local_packages/google_mlkit_barcode_scanning10

flutter:
  uses-material-design: true

  assets:
    - .env
